public with sharing class Black extends Man{
    public Black() {

   }
    

   String name; 
   String colour;
   override void say( System.debug('I'm black'););
  
   public override void eat(){
    System.debug('Black men eat elefants');
   }
   
   public void drink(){
    System.debug('Black men drink water');
   }
  public Black(String name, String colour){
    this.name = name;
    this.colour =colour;
   }
   List<Egyptian>egyptyans;
   List<Livian>livians;

}