public with sharing class Mammal extends Animal{
    public Mammal() {

    }
    override void say(System.debug('Muuu');
  
    public String species;
    public String colour;

   public override void eat(){
    System.debug('Mammals eat grass');
   }
   
   public void drink(){
    System.debug('Mammals drink water');
   }
  public Mammal(String species, String colour){
    this.species = species;
    this.colour = colour;

   }
   List<ArcticMammal>arcticMammals;
   List<AustralianMammal>australianMammals;
   
}