public with sharing class White extends Man{
    public White() {

    }

   String name; 
   String colour;
    override void say( System.debug('I'm white'););
  
   public override void eat(){
    System.debug('White men eat bread');
   }
   
   public void drink(){
    System.debug('White men drink vodka');
   }
  public White(String name, String colour){
    this.name = name;
    this.colour = colour;

   }
   List<Belarussian>belarusians;
   List<Ukrainian>ukrainians;
}