public with sharing class Yellow extends Man{
    public Yellow() {

    }
    String name; 
    String colour;


    override void say( System.debug('I'm yellow'););
  
   public override void eat(){
    System.debug('Yellow men eat rise');
   }
   
   public void drink(){
    System.debug('Yellow men drink sakaaay');
   }
   public Yellow(String name, String colour){
    this.name = name;
    this.colour = colour;

   }
   List<Chineese>chineese;
   List<Indian>indians;
}